---
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'sample/bin/aws-codedeploy-samples/**/*'
Metrics/AbcSize:
  Max: 40
Metrics/BlockLength:
  Max: 30
  Exclude:
    - '**/*spec.rb'
Metrics/ClassLength:
  Max: 300
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Max: 120
Style/ClassAndModuleChildren:
  Enabled: false
